### ISSUE TITLE
response(Post::paginate()); do not work

### ISSUE THREAD

**Issue by fey** [stephenlake/laravel-shovel#11]
Get `Call to a member function toArray() on array`

In controller
```php
    public function index()
    {
        //
        return response(Article::paginate());
    }
```
`api.php`
```php
Route::middleware(['ApiRequest', 'ApiResponse'])->get('/articles', 'ArticleResourceController@index');
```

Wrap with Resource work fine

`php -v`
` 7.3.7-2`
`Laravel Framework 5.8.30`
```
            "name": "stephenlake/laravel-shovel",
            "version": "v2.1.1",
```

**Comment by fey** [comment]
Error at `stephenlake/laravel-shovel/src/Http/Middleware/ApiResponse.php` line: `61`

**Comment by stephenlake** [comment]
Thanks for the report. Added unit tests to cover this. Please update to [2.1.2](https://github.com/stephenlake/laravel-shovel/releases/tag/v2.1.2).
