### ISSUE TITLE
[Idea] Add links for pagination navigation to the meta object

### ISSUE THREAD

**Issue by jpmurray** [stephenlake/laravel-shovel#6]
Something in the lines of (and akin to what we can see on the regular pagination json object fron Laravel)

```
"meta": {
    "code": 200,
    "status": "success",
    "message": "OK",
    "pagination": {
      "records": 10,
      "page": 1,
      "pages": 4,
      "limit": 3
      "first_page_url": "http://laravel.app?page=1",
      "last_page_url": "http://laravel.app?page=4",
      "next_page_url": "http://laravel.app?page=2",
      "prev_page_url": null,
    }
  },
```

**Comment by stephenlake** [comment]
Thanks @jpmurray. I'll add this as a config option as soon as I find some time.

**Comment by stephenlake** [comment]
Boiler created on [issue-#6](https://github.com/stephenlake/laravel-shovel/tree/issue-%236). Will complete this week.

**Comment by stephenlake** [comment]
Merged into master and included in [v1.0.4](https://github.com/stephenlake/laravel-shovel/releases/tag/v1.0.4).

**Comment by jpmurray** [comment]
Sounds absolutely perfect!

**Comment by jpmurray** [comment]
Got to play with it, it's really nice.

Just to add to the thinking mill, as for customizable URLs, I'd actually probably just want to see a possibility to _add_ to the parameters. For example, detecting that there is a token used in URL for example, I would add it automatically to the URL so it's less burden on the consumer part.

But yeah, as it is, it's already useful in itself! ;-)
